import type { PaidPuzzleSource, PuzzleSource } from '@/types/source.types'

const userAgentHeader = { 'User-Agent': 'CrosswordPWA/1.0 (+https://github.com/iAn-P1nt0/crossword-pwa)' }

export const FREE_SOURCES: PuzzleSource[] = [
  {
    id: 'wsj-daily',
    name: 'Wall Street Journal',
    description: 'Daily 15x15 puzzle inspired by WSJ print edition',
    homepage: 'https://www.wsj.com/news/life-arts/crossword',
    timezone: 'America/New_York',
    frequency: 'daily',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 1,
    defaultEnabled: true,
    download: {
      // Use the public herbach mirror which provides WSJ puzzles with YYMMDD naming
      url: 'https://herbach.dnsalias.com/WSJ/wsj{{YY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'usa-today',
    name: 'USA Today',
    description: 'USA Today daily crossword feed',
    homepage: 'https://puzzles.usatoday.com/',
    timezone: 'America/New_York',
    frequency: 'daily',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 2,
    defaultEnabled: true,
    download: {
      url: 'https://puzzles.usatoday.com/crossword/{{YYYY}}/{{MM}}/{{DD}}/usatoday{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'la-times',
    name: 'Los Angeles Times',
    description: 'LAT daily puzzle via Amuse Labs feed',
    homepage: 'https://www.latimes.com/games/crossword',
    timezone: 'America/Los_Angeles',
    frequency: 'daily',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 3,
    defaultEnabled: true,
    download: {
      url: 'https://cdn3.amuselabs.com/lat/crossword?id=lat{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'universal-crossword',
    name: 'Universal Crossword',
    description: 'Andrews McMeel syndicate universal crossword',
    homepage: 'https://www.uexpress.com/puzzles/universal-crossword',
    timezone: 'America/Chicago',
    frequency: 'daily',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 4,
    defaultEnabled: true,
    download: {
      url: 'https://cdn.amuselabs.com/universal/crossword?id=uc{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'newsday-stan-newman',
    name: 'Newsday (Stan Newman)',
    description: 'Newsday daily puzzle (Stan Newman editing)',
    homepage: 'https://www.newsday.com/crossword',
    timezone: 'America/New_York',
    frequency: 'daily',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 5,
    defaultEnabled: true,
    download: {
      url: 'https://cdn.newsday.com/puzzles/crossword/newsday{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'joseph-crosswords',
    name: 'Joseph Crosswords',
    description: 'Weekly cryptic from Joseph',
    homepage: 'https://josephcrosswords.com',
    timezone: 'America/New_York',
    frequency: 'weekly',
    category: 'free',
    format: 'ipuz',
    requiresAuth: false,
    authType: 'none',
    priority: 6,
    defaultEnabled: true,
    download: {
      url: 'https://josephcrosswords.com/puzzles/{{YYYY}}/{{MM}}/{{DD}}.ipuz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'ipuz',
    },
  },
  {
    id: 'jonesin-crosswords',
    name: "Jonesin' Crosswords",
    description: 'Weekly indie crossword by Matt Jones',
    homepage: 'http://www.jonesincrosswords.com/',
    timezone: 'America/Los_Angeles',
    frequency: 'weekly',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 7,
    defaultEnabled: true,
    download: {
      url: 'http://herbach.dnsalias.com/Jonesin/jonesin{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'erik-agard',
    name: 'Erik Agard Weekly',
    description: 'Indie puzzles from Erik Agard',
    homepage: 'https://erikagard.com/crosswords',
    timezone: 'America/New_York',
    frequency: 'weekly',
    category: 'free',
    format: 'ipuz',
    requiresAuth: false,
    authType: 'none',
    priority: 8,
    defaultEnabled: true,
    download: {
      url: 'https://erikagard.com/puzzles/{{YYYY}}/{{MM}}/{{DD}}.ipuz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'ipuz',
    },
  },
  {
    id: 'chronicle-higher-education',
    name: 'Chronicle of Higher Education',
    description: 'Weekly themed crossword from CHE',
    homepage: 'https://www.chronicle.com/newsletter/crossword',
    timezone: 'America/New_York',
    frequency: 'weekly',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 9,
    defaultEnabled: true,
    download: {
      url: 'https://chronicle.com/crossword/che{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
  {
    id: 'crosSynergy-wapo',
    name: 'CrosSynergy / Washington Post',
    description: 'Archive of CrosSynergy/WaPo puzzles',
    homepage: 'https://www.washingtonpost.com/crossword',
    timezone: 'America/New_York',
    frequency: 'daily',
    category: 'free',
    format: 'puz',
    requiresAuth: false,
    authType: 'none',
    priority: 10,
    defaultEnabled: true,
    download: {
      url: 'https://herbach.dnsalias.com/WaPo/wapo{{YYYY}}{{MM}}{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
  },
]

export const PAID_SOURCES: PaidPuzzleSource[] = [
  {
    id: 'nyt-premium',
    name: 'New York Times',
    description: 'NYT Crossword subscription feed',
    homepage: 'https://www.nytimes.com/crosswords',
    timezone: 'America/New_York',
    frequency: 'daily',
    category: 'paid',
    format: 'puz',
    requiresAuth: true,
    authType: 'cookie',
    priority: 1,
    defaultEnabled: true,
    download: {
      url: 'https://www.nytimes.com/svc/crosswords/v2/puzzle/standard/{{YYYY}}-{{MM}}-{{DD}}.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
    credentialHints: ['Set-cookie header from nytimes.com after logging in'],
  },
  {
    id: 'wsj-premium',
    name: 'WSJ Premium',
    description: 'Subscriber-only puzzles from WSJ',
    homepage: 'https://www.wsj.com/news/types/puzzles',
    timezone: 'America/New_York',
    frequency: 'weekly',
    category: 'paid',
    format: 'puz',
    requiresAuth: true,
    authType: 'cookie',
    priority: 2,
    defaultEnabled: true,
    download: {
      url: 'https://www.wsj.com/puzzles/crossword/{{YYYY}}/{{MM}}/{{DD}}/download.puz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'puz',
    },
    credentialHints: ['Requires active wsj.com subscription cookie'],
  },
  {
    id: 'guardian-cryptic',
    name: 'The Guardian',
    description: 'Guardian cryptic/quick crosswords via API',
    homepage: 'https://www.theguardian.com/crosswords',
    timezone: 'Europe/London',
    frequency: 'daily',
    category: 'paid',
    format: 'ipuz',
    requiresAuth: true,
    authType: 'api_key',
    priority: 3,
    defaultEnabled: true,
    download: {
      url: 'https://content.guardianapis.com/crosswords/{{YYYY}}/{{MM}}/{{DD}}?format=ipuz',
      method: 'GET',
      headers: userAgentHeader,
      format: 'ipuz',
    },
    credentialHints: ['Guardian Open Platform API key with crossword scope'],
  },
]

export const ALL_SOURCES: PuzzleSource[] = [...FREE_SOURCES, ...PAID_SOURCES]

export function getSourceById(id: string) {
  return ALL_SOURCES.find((source) => source.id === id)
}
